keep_files: ['assets/bundle.js', 'assets/style.css']
collections:
  posts:
    output: true
    permalink: /posts/:title.html
  pages:
    output: true
    permalink: /pages/:title.html

# site instance config
name: Douglas Duhaime
icon: /assets/images/me.jpg
github: http://github.com/duhaime
twitter: http://twitter.com/douglasduhaime
dark: 213, 58, 38
light: 255, 236, 179