collections:
  posts:
    output: true
    permalink: /posts/:title.html
  pages:
    output: true
    permalink: /pages/:title.html
  projects:
    output: false

basename: ''

keep_files:
  - 'assets/bundle.js'
  - 'assets/style.css'

exclude:
  - 'node_modules/'
  - 'utils/'

# specify plugins
plugins:
  - octopress-minify-html

# minify html
minify_html: false

# instant cello
name: Douglas Duhaime
url: http://douglasduhaime.com
title: Data Mining + Visualization
description: Working notes on data mining and interactive data visualization.
fallback_image: /assets/images/fallback.png
preview: /assets/images/preview/
github: duhaime
twitter: douglasduhaime
dark: 213, 58, 38
light: 255, 236, 179