# specify plugins
plugins:
  - octopress-minify-html

# minify all inlined css
sass:
  style: compressed

# minify html
minify_html: false

# live in the future and build what's missing
future: true

# bust html cache
bust_cache: true

# files to include
include:
  - _includes

# files to exclude
exclude:
  - .git/
  - Gemfile
  - Gemfile.lock

collections:
  records:
    output: true
    permalink: /:categories/:title.html

# site location
url: http://douglasduhaime.com
baseurl: ''
host: 0.0.0.0

# hello cello
title: Working notes & digital experiments
description: Working notes & digital experiments
fallback_image: /assets/images/douglas-duhaime.png
github: duhaime
