keep_files: ['assets/bundle.js', 'assets/style.css']
collections:
  posts:
    output: true
    permalink: /posts/:title.html
  pages:
    output: true
    permalink: /pages/:title.html
  projects:
    output: false

# site instance config
name: Douglas Duhaime
url: https://duhaime.github.io
title: Data Mining + Visualization
description: Working notes on data mining and interactive data visualization.
fallback_image: /assets/images/fallback.png
github: http://github.com/duhaime
twitter: http://twitter.com/douglasduhaime
dark: 213, 58, 38
light: 255, 236, 179