# specify plugins
plugins:
  - octopress-minify-html

# minify html
minify_html: true

# bust html cache
bust_cache: true

# files to keep and exclude
keep_files:
  - 'assets/bundle.js'
  - 'assets/style.css'
exclude:
  - 'node_modules/'
  - 'utils/'

# collections config
collections:
  posts:
    output: true
    permalink: /posts/:title.html
  pages:
    output: true
    permalink: /pages/:title.html
  projects:
    output: false

# site location
url: http://douglasduhaime.com
baseurl: ''

# hello cello
name: Douglas Duhaime
title: Data Mining + Visualization
description: Working notes on data mining and interactive data visualization.
fallback_image: /assets/images/fallback.png
github: duhaime
twitter: douglasduhaime
dark: 213, 58, 38
light: 255, 236, 179