keep_files: ['assets/bundle.js', 'assets/style.css', 'blog', 'about']
collections:
  posts:
    output: true
    permalink: /posts/:title.html
  pages:
    output: true
    permalink: /pages/:title.html
  projects:
    output: false

# site instance config
name: Douglas Duhaime
url: http://douglasduhaime.com
title: Data Mining + Visualization
description: Working notes on data mining and interactive data visualization.
fallback_image: /assets/images/fallback.png
github: duhaime
twitter: douglasduhaime
dark: 213, 58, 38
light: 255, 236, 179